In [9]:
import numpy

In [10]:
input_str = '59750530221324194853012320069589312027523989854830232144164799228029162830477472078089790749906142587998642764059439173975199276254972017316624772614925079238407309384923979338502430726930592959991878698412537971672558832588540600963437409230550897544434635267172603132396722812334366528344715912756154006039512272491073906389218927420387151599044435060075148142946789007756800733869891008058075303490106699737554949348715600795187032293436328810969288892220127730287766004467730818489269295982526297430971411865028098708555709525646237713045259603175397623654950719275982134690893685598734136409536436003548128411943963263336042840301380655801969822'

In [103]:
input_str = '12345678'

In [78]:
input_str = '80871224585914546619083218645595'

In [146]:
input_str = '19617804207202209144916044189917'

In [153]:
input_str = '69317163492948606335995924319873'

In [79]:
sig = numpy.array([int(d) for d in input_str])[:8]

In [81]:
size = len(sig)
transform = numpy.array([
    numpy.resize(
        numpy.repeat(
            [0,1,0,-1], i
        ), 9
    ) for i in range(1, 9)]).T[1:]

In [82]:
transform

array([[ 1,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  1,  0,  0,  0,  0,  0,  0],
       [-1,  1,  1,  0,  0,  0,  0,  0],
       [ 0,  0,  1,  1,  0,  0,  0,  0],
       [ 1,  0,  1,  1,  1,  0,  0,  0],
       [ 0, -1,  0,  1,  1,  1,  0,  0],
       [-1, -1,  0,  1,  1,  1,  1,  0],
       [ 0,  0,  0,  0,  1,  1,  1,  1]])

In [83]:
for phase in range(100):
    sig = abs(sig.dot(transform))%10
    print(sig)

[1 4 6 2 9 8 6 4]
[2 4 7 5 7 8 0 4]
[2 3 9 0 9 2 4 4]
[2 6 8 5 9 0 8 4]
[5 6 2 2 1 2 2 4]
[2 4 5 7 9 8 6 4]
[0 5 1 0 7 8 0 4]
[6 2 8 5 9 2 4 4]
[3 4 2 0 9 0 8 4]
[2 2 1 7 1 2 2 4]
[0 1 9 2 9 8 6 4]
[6 4 0 5 7 8 0 4]
[3 4 2 0 9 2 4 4]
[6 0 1 5 9 0 8 4]
[6 7 5 2 1 2 2 4]
[0 8 8 7 9 8 6 4]
[5 2 4 0 7 8 0 4]
[8 2 1 5 9 2 4 4]
[2 3 5 0 9 0 8 4]
[2 0 4 7 1 2 2 4]
[3 0 2 2 9 8 6 4]
[4 2 3 5 7 8 0 4]
[8 3 5 0 9 2 4 4]
[8 2 4 5 9 0 8 4]
[5 2 8 2 1 2 2 4]
[4 6 1 7 9 8 6 4]
[6 7 7 0 7 8 0 4]
[6 6 4 5 9 2 4 4]
[7 4 8 0 9 0 8 4]
[0 4 7 7 1 2 2 4]
[8 7 5 2 9 8 6 4]
[6 2 6 5 7 8 0 4]
[7 0 8 0 9 2 4 4]
[4 2 7 5 9 0 8 4]
[2 1 1 2 1 2 2 4]
[0 2 4 7 9 8 6 4]
[1 8 0 0 7 8 0 4]
[8 0 7 5 9 2 4 4]
[6 1 1 0 9 0 8 4]
[6 6 0 7 1 2 2 4]
[5 2 8 2 9 8 6 4]
[0 4 9 5 7 8 0 4]
[2 5 1 0 9 2 4 4]
[6 0 0 5 9 0 8 4]
[7 8 4 2 1 2 2 4]
[2 8 7 7 9 8 6 4]
[2 1 3 0 7 8 0 4]
[6 4 0 5 9 2 4 4]
[1 2 4 0 9 0 8 4]
[2 2 3 7 1 2 2 4]
[2 1 1 2 9 8 6 4]
[4 2 2 5 7 8 0 4]
[9 4 4 0 9 2 4 4]
[0 2 3 5 9 0 8 4]
[2 3 7 2 1 2 2 4]
[6 6 0 7 9

In [142]:
sig

array([2, 4, 1, 7, 6, 1, 7, 6, 4, 8, 0, 9, 1, 9, 0, 4, 6, 1, 1, 4, 0, 3,
       8, 7, 6, 3, 1, 9, 5, 5, 9, 5])

In [84]:
a.T[1:].dot(input_a) % 10

array([1, 2, 4, 7, 3, 3, 9, 6])

In [86]:
input_a.dot(a.T[1:].T)

array([ 1,  2,  4,  7, 13, 13, 19, 26])

In [87]:
a

array([[ 0,  1,  0, -1,  0,  1,  0, -1,  0],
       [ 0,  0,  1,  1,  0,  0, -1, -1,  0],
       [ 0,  0,  0,  1,  1,  1,  0,  0,  0],
       [ 0,  0,  0,  0,  1,  1,  1,  1,  0],
       [ 0,  0,  0,  0,  0,  1,  1,  1,  1],
       [ 0,  0,  0,  0,  0,  0,  1,  1,  1],
       [ 0,  0,  0,  0,  0,  0,  0,  1,  1],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  1]])

In [88]:
a.T[1:].T

array([[ 1,  0, -1,  0,  1,  0, -1,  0],
       [ 0,  1,  1,  0,  0, -1, -1,  0],
       [ 0,  0,  1,  1,  1,  0,  0,  0],
       [ 0,  0,  0,  1,  1,  1,  1,  0],
       [ 0,  0,  0,  0,  1,  1,  1,  1],
       [ 0,  0,  0,  0,  0,  1,  1,  1],
       [ 0,  0,  0,  0,  0,  0,  1,  1],
       [ 0,  0,  0,  0,  0,  0,  0,  1]])

In [97]:
abs(input_a.dot(a.T[1:]))%10

array([4, 8, 2, 2, 6, 1, 5, 8])

In [1]:
input_str = '03036732577212944063491565474664'

In [11]:
m = input_str*10000

In [15]:
offset = int(input_str[:7])

In [63]:
sig = numpy.array([int(d) for d in m[offset: offset+8]])

In [64]:
sig

array([4, 6, 3, 5, 2, 6, 7, 1])

In [19]:
offset + 8

5975061

In [20]:
numpy.array(
    numpy.resize(
            numpy.repeat(
                [0,1,0,-1], offset
            ), offset + 9
        )[offset:offset + 9]
    

array([1, 1, 1, 1, 1, 1, 1, 1, 1])

In [76]:
transforms = numpy.array([
        numpy.repeat(
            [0,1,0,-1], i
        )[offset:offset+9] for i in range(offset, offset+8)]).T[1:]

In [66]:
transforms

array([[1, 1, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 0],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])

In [65]:
sig

array([4, 6, 3, 5, 2, 6, 7, 1])

In [68]:
t1 = '03036732577212944063491565474664'

In [69]:
offset = int(t1[:7])

In [71]:
t1x = t1*10000

In [74]:
sig = numpy.array([int(d) for d in t1x[offset:offset+8]])

In [75]:
sig

array([5, 4, 7, 4, 6, 6, 4, 0])